# -*- coding: utf-8 -*-
"""Aula_14_LPDA_SENAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11xjMRqU5L3tQS05fr7IXtO0nm7LaMnxd

#Funções

#Funções Trigonométricas
"""

#Função Seno
import math

#Seno de 60 graus
print(math.sin(math.radians(60)))
#Seno de pi/radianos
print(math.sin(math.pi/3))

#Função Seno
import numpy as np

#Seno de 60 graus
print(np.sin(math.radians(60)))
#Seno de pi/radianos
print(np.sin(math.pi/3))

#Função Cosseno
import math

#Seno de 60 graus
print(math.cos(math.radians(60)))
#Seno de pi/radianos
print(math.cos(math.pi/3))

#Função Cosseno
import numpy as np

#Seno de 60 graus
print(np.cos(math.radians(60)))
#Seno de pi/radianos
print(np.cos(math.pi/3))

#Função Tangente
import math

#Seno de 60 graus
print(math.tan(math.radians(60)))
#Seno de pi/radianos
print(math.tan(math.pi/3))

#Função Tangente
import numpy as np

#Seno de 60 graus
print(np.tan(math.radians(60)))
#Seno de pi/radianos
print(np.tan(math.pi/3))

"""#Função Seno"""

import numpy as np
import matplotlib.pyplot as plt

fsin=np.sin(np.linspace(0,360,360) * np.pi / 180. )
x=np.linspace(0,360,360)

#Gráfico
plt.figure().set_figheight(2,3)
plt.plot(x, fsin)
plt.xlabel('x', fontsize=15)
plt.ylabel('sin(x)', fontsize=15)
plt.title('Função Seno')
plt.legend(['f(x)=sin(x)'])
plt.show()

"""#Função Cosseno"""

import numpy as np
import matplotlib.pyplot as plt

fcos=np.cos(np.linspace(0,360,360) * np.pi / 180. )
x=np.linspace(0,360,360)

#Gráfico
plt.figure().set_figheight(2,3)
plt.plot(x, fcos)
plt.xlabel('x', fontsize=15)
plt.ylabel('cos(x)', fontsize=15)
plt.title('Função Cosseno')
plt.legend(['f(x)=cos(x)'])
plt.show()

"""#Função Tangente"""

import numpy as np
import matplotlib.pyplot as plt

ftan=np.tan(np.linspace(0,360,360) * np.pi / 180 )
print(np.tan(np.pi/ 2))
x=np.linspace(0,360,360)

#Gráfico
plt.figure().set_figheight(2,3)
plt.plot(x, ftan)
plt.xlabel('x', fontsize=15)
plt.ylabel('tan(x)', fontsize=15)
plt.title('Função Tangente')
plt.legend(['f(x)=tan(x)'])
plt.ylim(-20, 20)
plt.show()

"""Exercícios"""

import numpy as np
import matplotlib.pyplot as plt

fsin=np.sin(np.linspace(0,360,360) * np.pi / 180. )+ np.ones(360) * 2
x=np.linspace(0,360,360)

#Gráfico
plt.figure().set_figheight(2,3)
plt.plot(x, fsin)
plt.xlabel('x', fontsize=15)
plt.ylabel('sin(x)', fontsize=15)
plt.title('Função Seno')
plt.legend(['f(x)=sin(x)'])
plt.show()

import numpy as np
import matplotlib.pyplot as plt

fcos=np.cos(2*(np.linspace(0,360,360) * np.pi / 180. ))+ np.ones(360) * (-3)
x=np.linspace(0,360,360)

#Gráfico
plt.figure().set_figheight(2,3)
plt.plot(x, fcos)
plt.xlabel('x', fontsize=15)
plt.ylabel('cos(x)', fontsize=15)
plt.title('Função Cosseno')
plt.legend(['f(x)=cos(x)'])
plt.show()

#Subplot
import matplotlib.pyplot as plt
import numpy as np

#Gráfico
#Subplot 1
fsin=np.sin(np.linspace(0,360,360) * np.pi / 180. )
x=np.linspace(0,360,360)

plt.subplot(2, 3, 1)
plt.plot(x, fsin)
plt.xlabel('x', fontsize=15)
plt.ylabel('sin(x)', fontsize=15)
plt.title('f(x)=sin(x)')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.tight_layout(pad=5.0)


#Subplot 2
fsin=np.sin(np.linspace(0,360,360) * np.pi / 180. )+ np.ones(360) * 3
x=np.linspace(0,360,360)

plt.subplot(2, 3, 2)
plt.plot(x, fsin)
plt.xlabel('x', fontsize=15)
plt.ylabel('sin(x)+3', fontsize=15)
plt.title('f(x)=sin(x)+3')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')


#Subplot 3
fsin=np.sin(np.linspace(0,360,360) * np.pi / 180. )+ np.ones(360) * (-3)
x=np.linspace(0,360,360)

plt.subplot(2, 3, 3)
plt.plot(x, fsin)
plt.xlabel('x', fontsize=15)
plt.ylabel('sin(x)-3', fontsize=15)
plt.title('f(x)=sin(x)-3')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')


#Subplot 4
fsin=np.sin(3*(np.linspace(0,360,360) * np.pi / 180. ))
x=np.linspace(0,360,360)

plt.subplot(2, 3, 4)
plt.plot(x, fsin)
plt.xlabel('x', fontsize=15)
plt.ylabel('sin(3x)', fontsize=15)
plt.title('f(x)=sin(3x)')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')


#Subplot 5
fsin=np.sin((1/3)*(np.linspace(0,360,360) * np.pi / 180. ))
x=np.linspace(0,360,360)

plt.subplot(2, 3, 5)
plt.plot(x, fsin)
plt.xlabel('x', fontsize=15)
plt.ylabel('sin(x/3)', fontsize=15)
plt.title('f(x)=sin(x/3)')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')



#Subplot 6
fsin=np.sin((3)*(np.linspace(0,360,360) * np.pi / 180. ))+ np.ones(360) * (4)
x=np.linspace(0,360,360)

plt.subplot(2, 3, 6)
plt.plot(x, fsin)
plt.xlabel('x', fontsize=15)
plt.ylabel('sin(3x)+4', fontsize=15)
plt.title('f(x)=sin(3x)+4')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.show()

#Subplot
import matplotlib.pyplot as plt
import numpy as np

#Gráfico
#Subplot 1
fsin=np.sin(2*np.linspace(0,360,360) * np.pi / 180. )
x=np.linspace(0,360,360)

plt.subplot(2, 3, 1)
plt.plot(x, fsin)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.tight_layout(pad=5.0)


#Subplot 2
fcos=np.cos(np.linspace(0,360,360) * np.pi / 180. )-4
x=np.linspace(0,360,360)

plt.subplot(2, 3, 2)
plt.plot(x, fcos)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.show()

"""#Função Polinomial"""

import numpy as np
import matplotlib.pyplot as plt
import math

x=np.arange(-60, 60, 1, dtype=int)
y=x**3+3*x+5

#Plot
plt.plot(x, y)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Função Polinomial')
plt.show()

"""#Função Logarítmica"""

#Logarítmo de um número
import math

x=math.log(16,2)
print('O Log de 16 na base 2 é:',x)

import numpy as np
import math
import matplotlib.pyplot as plt

x=np.linspace(0.1,10,30)
y=np.log(x)

plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Função Logarítmica')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.plot(x,y)
plt.show()

"""#Exercícios"""

import numpy as np
import matplotlib.pyplot as plt

plt.figure().set_figheight(3,3)
#Gráfico
#Subplot 1
x=np.linspace(0.1,25,50)
y1=np.log2(x)

plt.subplot(1, 3, 1)
plt.plot(x, y1)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('F. Log base 2')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.tight_layout(pad=5)

#Subplot 2
y2=np.emath.logn(5,x)

plt.subplot(1, 3, 2)
plt.plot(x, y2)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('F. Log base 5')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')

#Subplot 3
y3=np.emath.logn((1/3),x)

plt.subplot(1, 3, 3)
plt.plot(x, y3)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('F. Log base 1/3')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.show()

"""#Função Exponencial"""

#Exponencial de um número
x=3**4
print('O exponencial de 4 na base 3 é:',x)

#Exponencial de um número
import math

x=math.exp(4)
print('O exponencial de 4 na base e é:',x)

import numpy as np
import math
import matplotlib.pyplot as plt

x=np.linspace(0.1,10,30)
y=2.**x

plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Função Exponencial')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.plot(x,y)
plt.show()