# -*- coding: utf-8 -*-
"""Aula_5_LPDA_SENAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r15UfAHFYLtMc71fUKhC09pvignzbOBC

#Matrizes
"""

import numpy as np

matriz= np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)
matriz.shape

matriz[1,2]

#Matriz com números aleatórios
import numpy as np

#Exemplo Matriz quadrada de ordem 2
A=np.random.rand(2,2)
print('Matriz A: ',A)

#Exemplo Matriz de dimensão qualquer
B=np.random.rand(3,4)
print('Matriz B: ',B)

#Matriz Identidade
import numpy as np
I=np.identity(3)
print(I)

#Matriz Transposta
import numpy as np

A=np.random.rand(3,2)

A_transpose=np.transpose(A)

print(A)
print(A_transpose)

"""#Operações com Matrizes"""

#Exemplo
import numpy as np

A= np.array([[5,-1,3], [0,8,-2]])
B= np.array([[7,9,3], [-5,2,1]])

#Adição
soma=A+B
print('A soma das matrizes é: ',soma)

#Subtração
subt=A-B
print('A subtração das matrizes é: ',subt)

#Multiplicação por uma constante
multc=15*A
print('A multiplicação por uma constante é: ',multc)

#Exercício
import numpy as np

A= np.array([[0,-9],[-5,8],[-15,13]])
B= np.array([[3,-19],[-4,7],[14,-11]])

#Adição
soma=A+B
print('A soma das matrizes é: ',soma)

#Subtração
subt=A-B
print('A subtração das matrizes é: ',subt)

#Multiplicação por uma constante
multc=15*A
print('A multiplicação por uma constante é: ',multc)

#Exemplo
import numpy as np

A= np.array([[1, -3, 5], [8, 0, 3]])
B= np.array([[2, 4], [6, 10],[1,5]])

#Multiplicação por uma constante
multm=np.matmul(A, B)
print('A multiplicação entre matrizes é: ',multm)

#Exercício
import numpy as np

A= np.array([[0,-2,4,1], [5,-3,0,2],[-1,0,1,-7]])
B= np.array([[1,3], [-12, 10],[20,0],[7,-15]])

#Multiplicação por uma constante
multm=np.matmul(A, B)
print('O elemento c31 é: ',multm[2,0])

"""#Determinante de uma Matriz"""

#Exemplo
import numpy as np

A=np.array([[1,9,5],[3,7,8],[10,4,2]])

detA=np.linalg.det(A)

print('O determinante da matriz é: ',detA)

#Exercício 1
import numpy as np

A=np.array([[2,5,-3],[1,4,7],[-2,0,6]])

detA=np.linalg.det(A)

print('O determinante da matriz é: ',detA)

#Exercício 2
import numpy as np
import math

B=np.array([[math.sqrt(2),2,1],[-1,math.sqrt(3),3],[3,2,math.sqrt(6)]])

detB=np.linalg.det(B)

print('O determinante da matriz é: ',detB)

"""#Matriz Inversa"""

import numpy as np

A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

invA=np.linalg.inv(A)
print('A inversa da matriz A é: ', invA)