# -*- coding: utf-8 -*-
"""Aula_9_LPDA_SENAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QiFi6vzQCzgIQYciV1GtoTS9M5rHNj4m

#Funções

#Função Linear
"""

#Função Linear
import numpy as np

#Variáveis x
x=np.array([-2,-1,0,1,2])

#Lei de formação
y=2*x

print(y)

#Gráfico
import matplotlib.pyplot as plt
import numpy as np

#plt.figure().set_figheight(3,4)
plt.plot(x, y)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Função Linear')
plt.legend(['y=2x'])
plt.show()

"""#Função Afim"""

#Função Afim - Coeficiente Angular
import numpy as np

#Variáveis x
x=np.array([-2,-1,0,1,2])

#Lei de formação
y1=-5*x+1    #a=-5 e b=+1
y2=-1*x+1    #a=-1 e b=+1
y3=-0.5*x+1  #a=-0.5 e b=+1

#subplot 1:
plt.plot(x,y1)
plt.plot(x,y2)
plt.plot(x,y3)
plt.legend(['y=-5x+1','y=-1x+1','y=-0.5x+1'])
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Coeficiente Angular')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.show()

#Função Afim - Coeficiente Linear
import numpy as np

#Variáveis x
x=np.array([-2,-1,0,1,2])

#Lei de formação
y1=2*x+3  #a=2 e b=+3
y2=2*x    #a=2 e b=0
y3=2*x-3  #a=2 e b=-3

#subplot 1:
plt.plot(x,y1)
plt.plot(x,y2)
plt.plot(x,y3)
plt.legend(['y=2x+3','y=2x','y=2x-3'])
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Coeficiente Linear')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.show()

#Exercício
import numpy as np
import matplotlib.pyplot as plt

Ax=int(input('Insira Ax: '))
Ay=int(input('Insira Ay: '))
Bx=int(input('Insira Bx: '))
By=int(input('Insira By: '))

#Coeficiente Linear
a=(By-Ay)/(Bx-Ax)

#Coeficiente Angular
b=Ay-(a*Ax)

print('A lei de formação é: y =',a,'x+',b)

x=np.arange(-10, 10, 1, dtype=int)
y=a*x+b

#Plot
plt.plot(x, y)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('Função Afim')
plt.show()

"""#Subplot"""

import matplotlib.pyplot as plt
import numpy as np

#plot 1:
#plt.figure().set_figheight(2,3)
x = np.linspace(-10,10,50)
y1 = 2*x+6
plt.subplot(2, 2, 1)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('1º Equação')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.plot(x,y1)

#plot 2:
y2 = -3*x+1
plt.subplot(2, 2, 2)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('2º Equação')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.plot(x,y2)

#plot 3:
y3 = x-(1/5)
plt.subplot(2, 2, 3)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('3º Equação')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.plot(x,y3)

#plot 4:
y4 = x-(1/5)
plt.subplot(2, 2, 3)
plt.xlabel('x', fontsize=15)
plt.ylabel('y', fontsize=15)
plt.title('3º Equação')
plt.axhline(y=0, color='k')
plt.axvline(x=0, color='k')
plt.plot(x,y3)

plt.tight_layout(pad=3.0)