# -*- coding: utf-8 -*-
"""Aula_4_LPDA_SENAI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m01qnjgh5Txdr2cSlpvy43SqHp_glg_t

**negrito**#Biblioteca Numpy
"""

#Criar um vetor
import numpy as np
vetor = np.array([1,2,3,4,5,6,7,8])
print(vetor)

#Selecionar um elemento do vetor
vetor[2]

#Módulo de um vetor
modulo = np.linalg.norm(vetor)
print(modulo)

import numpy as np
vetor = np.array([-55,12])
modulo = np.linalg.norm(vetor)
print(modulo)

import numpy as np
vetor = np.array([11,-23,-4])
modulo = np.linalg.norm(vetor)
print(modulo)

#Transposto de um vetor
import numpy as np
#Vetor 1D
vetor = np.array([11,-23,-4])

# Converter um vetor 1D para 2D com formato (3, 1)
vetor_2d = vetor[:, np.newaxis]

# Transposto do vetor 2D
transposed_vetor_2d = np.transpose(vetor_2d)

print("Vetor original:\n", vetor_2d)
print("Vetor transposto:\n", transposed_vetor_2d)

"""#Operações com Vetor"""

import numpy as np
u = np.array([-3,-5])
v = np.array([6,27])

#Adição
soma=u+v
print('A soma dos vetores é:',soma)
#Subtração
subt=u-v
print('A subtração dos vetores é:',subt)

import numpy as np
u = np.array([-3,-5])
v = np.array([6,27])

#Multiplicação
multp=9*u
print('A multiplicação é:',multp)
#Multiplicação por uma fração
multpfra=(1/3)*v
print('A multiplicação por fração é:',multpfra)

"""Resolução de Exercícios

"""

import numpy as np
u = np.array([2,(5/3)])
v = np.array([-1,7])

#Adição
soma=u+v
print('A soma dos vetores é:',soma)
#Subtração
subt=u-v
print('A subtração dos vetores é:',subt)

import numpy as np
u = np.array([2,(5/3)])
v = np.array([-1,7])

#Multiplicação
multp=3*u
print('A multiplicação é:',multp)
#Multiplicação por uma fração
multpfra=(1/5)*v
print('A multiplicação por fração é:',multpfra)

"""#Resultante de um Vetor"""

import numpy as np
import math

#Vetores A e B
A = np.array([-2,3])
B = np.array([7,4])

#Módulo dos vetores A e B
modA = np.linalg.norm(A)
print(modA)
modB = np.linalg.norm(B)
print(modB)

#Cosseno de 135°
cos135=math.cos(math.radians(135))

#Cálculo Resultante
R2=(modA**2)+(modB**2)+(2*modA*modB*cos135)
R = math.sqrt(R2)
print('A resultante R é: ',R)

"""#Produto Escalar"""

#Exercício 1
import numpy as np
import math

#Vetores A e B
A = np.array([5,4,2])
B = np.array([1,3,-12])

#1º opção - Produto Escalar
PE=(A[0]*B[0])+(A[1]*B[1])+(A[2]*B[2])

#2º opção - Produto Escalar
PE2=np.dot(A,B)

print('O produto escalar é:',PE)
print('O produto escalar é:',PE2)